accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.signup_view, name='register'),
    # path('logout/', auth_views.LogoutView.as_view(method='GET'), name="logout"),
    path('logout/', views.custom_logout, name="logout"),
    path('sign_in', views.sign_in, name='sign_in'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('web.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

web/urls.py
from django.urls import path 
from . import views

app_name = 'web'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('blog/', views.blog, name='blog'),
    path('contact_info/', views.contact_info, name='contact_info'),
    path('departments/', views.departments, name='departments'),
    path('doctor/', views.doctor, name='doctor'),
    path('appointment/', views.appointment, name='appointment'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('login/', views.login, name='login'),
    path('medicine/', views.medicine, name='medicine'),
    #path('signup/', views.signup, name='signup'),
    path('register/', views.register, name='register'),
    path('booking/<str:doctor_id>/', views.book_doctor, name='booking'),
    
    
]

web/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
  {% include 'common/header1.html'   %}
{% endblock %}
{% block content %}

    <!-- header section end -->
    <!-- about section start -->
    <div class="about_section layout_padding">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="about_taital">
              <h4 class="about_text">About</h4>
              <h1 class="highest_text">The Highest provide health care</h1>
              <p class="lorem_text">
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
                The point of using Lorem Ipsum is that it has a more-or-less
                normal distribution of letters, as opposedIt is a long
                established fact that a reader will be distracted by the
                readable content of a page when looking at its layout. The point
                of using Lorem Ipsum is that it has a more-or-less normal
                distribution of letters, as opposed
              </p>
              <div class="read_bt"><a href="#">Read More</a></div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="image_2" href="#"><img src="{%static 'images/img-2.png' %}" /></div>
          </div>
        </div>
      </div>
    </div>

  {% endblock %}
   

web/templates/appointment.html
<!-- {% extends 'base.html' %} -->
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/bootstrapappoint.min.css' %}">
<link rel="stylesheet" href="{% static 'css/datepickerappoint.css' %}">
<link rel="stylesheet" href="{% static 'css/styleappoint.css' %}">

<!-- {% include 'common/header1.html' %} -->

{% endblock %}
{% block content %}





<div class="inner-layer">
  <img>
  <div class="container">
    <div class="row no-margin">
      <div class="col-sm-7">
        <div class="content">
          <h1>Book You Appointment Now and Save your time</h1>
          <p>The Newlife Hospital is a 300 bed multispecialty Hospital in Kenya located in Runda, Nairobi Kenya. We offer patient focused, world class medical treatment and accord the highest stardards of medical care to all our patients indiscriminately. </p>
          <h1>For Help Call : +254 741 594 863</h1>
        </div>
      </div>
      <div class="col-sm-5">
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-data">
            <div class="form-head">
              <h2>Book Appointemnt</h2>
            </div>
            <div class="form-body">
              <div class="row form-row">
                <input type="text" placeholder="Enter Full name" class="form-control">
              </div>
              <div class="row form-row">
                <input type="text" placeholder="Enter Mobile Number" class="form-control">
              </div>
              <div class="row form-row">
                <input type="text" placeholder="Enter Email Adreess" class="form-control">
              </div>
              <div class="row form-row">
                <select id="doctor-dropdown" class="form-control">
                  <option value="">Select Doctor</option>
                  {% for doctor in doctors %}
                    <option value="{{ doctor.id }}">{{ doctor.name }}</option>
                  {% endfor %}
                </select>
              </div>
              
              <div class="row form-row">
                <input id="dat" type="text" placeholder="Appointment Date" class="form-control">
              </div>

              <h6>Address Details</h6>

              <div class="row form-row">
                <div class="col-sm-6">
                  <input type="text" placeholder="Enter Area" class="form-control">
                </div>
                <div class="col-sm-6">
                  <input type="text" placeholder="Enter City" class="form-control">
                </div>
              </div>
              <div class="row form-row">
                <div class="col-sm-6">
                  <input type="text" placeholder="Enter State" class="form-control">
                </div>
                <div class="col-sm-6">
                  <input type="text" placeholder="Postal Code" class="form-control">
                </div>
              </div>

              <div class="row form-row">
                <button class="btn btn-success btn-appointment" type="submit">
                  Book Appointment
                </button>

              </div>

            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jqueryappoint-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popperappoint.min.js' %}"></script>
<script src="{% static 'js/bootstrapappoint.min.js' %}"></script>
<script src="{% static 'js/bootstrapappoint-datepicker.js' %}"></script>

<script>
  $(document).ready(function () {
    $("#dat").datepicker();
  })
</script>



{% endblock %}

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


  <header>
    {% block header %}
    {% endblock %}
  </header>


<body>
  <!-- header section start -->
  <div class="header_section">
    <nav class="destop_header navbar navbar-expand-lg navbar-light bg-light">
      <div class="logo"></div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'web:index' %}">Home</a>
          </li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'web:about' %}">About</a></li>
          <li class="nav-item"><a class="logo_main" href="{% url 'web:index' %}"><img src="{%static 'images/logo.png' %}" /></a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'web:doctor' %}">Doctor</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'web:departments' %}">Departments</a> </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'web:blog' %}">Blog</a></li>
          <!-- <li class="nav-item"> <a class="nav-link" href="{% url 'web:contact_info' %}">Contact us</a>  </li> -->
          <li class="nav-item"><a class="nav-link" href="#"><img src="{%static 'images/search-icon.png' %}" /></a></li>
          <li class="nav-item {% if nav == 'contact' %} active {% endif %}"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:register' %}">LOGIN/REGISTER</a></li>
          {% endif %}
          
          <li class="nav-item {% if nav == 'contact' %} active {% endif %}"><a class="nav-link" href="{% url 'web:contact_info' %}">Contact us</a></li>
        </ul>
      </div>
    </nav>
    <nav class="mobile_header navbar navbar-expand-lg navbar-light bg-light">
      <div class="logo">
        <a href="{% url 'web:index' %}"><img src="{%static 'images/logo.png' %}" /></a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent2"
        aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent2">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"> <a class="nav-link" href="{% url 'web:index' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'web:about' %}">About</a> </li>
          <li class="nav-item"><a class="logo_main" href="{% url 'web:index' %}"><img src="{%static 'images/logo.png' %}" /></a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'web:doctor' %}">Doctor</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'web:departments' %}">Departments</a> </li>
          <li class="nav-item"><a class="nav-link" href="{% url 'web:blog' %}">Blog</a></li>
          <li class="nav-item"> <a class="nav-link" href="{% url 'web:contact_info' %}">Contact</a>  </li>
          <li class="nav-item"><a class="nav-link" href="#"><img src="{%static 'images/search-icon.png' %}" /></a></li>
          <li class="nav-item {% if nav == 'contact' %} active {% endif %}"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:register' %}">LOGIN/REGISTER</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>

  {% block content %} {% endblock %}

  <div class="info_section layout_padding">
    <div class="container">
      <div class="info_content">
        <div>
          <div class="row">
            <div class="col-md-4">
              <div class="d-flex">
                <h5>Medical Care</h5>
              </div>
              <div class="d-flex">
                <ul>
                  <li>
                    <a href="{% url 'web:about' %}"> About Us </a>
                  </li>
                  <li>
                    <a href=""> About services </a>
                  </li>
                  <li>
                    <a href="{% url 'web:departments' %}"> About Departments </a>
                  </li>
                  <li>
                    <a href=""> Services </a>
                  </li>
                  <li>
                    <a href="{% url 'web:contact_info' %}"> Contact Us </a>
                  </li>
                </ul>
                <ul class="ml-3 ml-md-5">
                  <li>
                    <a href=""> Cancer Oncology </a>
                  </li>
                  <li>
                    <a href=""> Dental Surgery </a>
                  </li>
                  <li>
                    <a href=""> Diagnose & Research </a>
                  </li>
                  <li>
                    <a href="{% url 'web:medicine' %}"> Drug / Medicines </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-4">
              <div class="d-flex">
                <h5>The Services</h5>
              </div>
              <div class="d-flex">
                <ul>
                  <li>
                    <a href="{% url 'web:about' %}"> About Us </a>
                  </li>
                  <li>
                    <a href="{% url 'web:about' %}"> About services </a>
                  </li>
                  <li>
                    <a href="{% url 'web:departments' %}"> About Departments </a>
                  </li>
                  <li>
                    <a href=""> Services </a>
                  </li>
                  <li>
                    <a href="{% url 'web:contact_info' %}"> Contact Us </a>
                  </li>
                </ul>
                <ul class="ml-3 ml-md-5">
                  <li>
                    <a href=""> Cancer Oncology </a>
                  </li>
                  <li>
                    <a href=""> Dental Surgery </a>
                  </li>
                  <li>
                    <a href=""> Diagnose & Research </a>
                  </li>
                  <li>
                    <a href="{% url 'web:medicine' %}"> Drug / Medicines </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-4">
              <div class="d-flex">
                <h5>Departments</h5>
              </div>
              <div class="d-flex">
                <ul>
                  <li>
                    <a href="{% url 'web:about' %}"> About Us </a>
                  </li>
                  <li>
                    <a href=""> About services </a>
                  </li>
                  <li>
                    <a href="{% url 'web:departments' %}"> About Departments </a>
                  </li>
                  <li>
                    <a href=""> Services </a>
                  </li>
                  <li>
                    <a href="{% url 'web:contact_info' %}"> Contact Us </a>
                  </li>
                </ul>
                <ul class="ml-3 ml-md-5">
                  <li>
                    <a href=""> Cancer Oncology </a>
                  </li>
                  <li>
                    <a href=""> Dental Surgery </a>
                  </li>
                  <li>
                    <a href=""> Diagnose & Research </a>
                  </li>
                  <li>
                    <a href="{% url 'web:medicine' %}"> Drug / Medicines </a>
                  </li>
                  <li>
                    <a href="{% url 'web:appointment' %}">
                      Book Appointment
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="d-flex flex-column flex-lg-row justify-content-between align-items-center align-items-lg-baseline">
          <div class="social-box">
            <a href="">
              <img src="{%static 'images/fb-icon.png' %}" alt="" />
            </a>

            <a href="">
              <img src="{%static 'images/twitter-icon.png' %}" alt="" />
            </a>
            <a href="">
              <img src="{%static 'images/linkedin-icon.png' %}" alt="" />
            </a>
            <a href="">
              <img src="{%static 'images/instagram-icon.png' %}" alt="" />
            </a>
          </div>
          <div class="form_container mt-5">
            <form action="">
              <label for="subscribeMail"> Newsletter </label>
              <input type="email" placeholder="Enter Your email" id="subscribeMail" />
              <button type="submit">Subscribe</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end info section -->
  <!-- footer section end -->
  <!-- copyright section start -->
  <div class="copyright_section">
    <div class="container">
      <p class="copyright">2020 All Rights Reserved. Design by ....</p>
    </div>
  </div>
  <!-- copyright section end -->
  <!-- Javascript files-->
  <script src="{%static 'js/jquery.min.js' %}"></script>
  <script src="{%static 'js/popper.min.js' %}"></script>
  <script src="{%static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{%static 'js/jquery-3.0.0.min.js' %}"></script>
  <script src="{%static 'js/plugin.js' %}"></script>
  <!-- sidebar -->
  <script src="{%static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{%static 'js/custom.js' %}"></script>
  <!-- javascript -->
  <script src="{% static 'js/owl.carousel.js' %}"></script>
  <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
  

  
</body>

</html>

web/templates/base1.html
{% extends 'base.html' %}

{% block content %}


{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>Appointment Booking </title>


    <!-- Web Fonts -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin">

    <!-- CSS Global Compulsory -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- CSS Header and Footer -->
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{% static 'plugins/line-icons-pro/styles.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/line-icons/line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/sky-forms-pro/skyforms/css/sky-forms.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css' %}">

    <!-- CSS Customization -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

</head>

<body>
    <div class="wrapper">
        <!--=== Header v1 ===-->
        <div class="header-v1">
            <!-- Topbar -->
            <div class="topbar-v1">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <ul class="list-inline top-v1-contacts">
                                <li>
                                    <i class="fa fa-envelope"></i> Email: unityhospital@gmail.com
                                </li>
                                <li>
                                    <i class="fa fa-phone"></i> Contact no : 88666 00555
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--=== Heading ===-->

        {% block content1 %}

        {% endblock %}


    </div><!--/wrapper-->

    <!-- Java scripts -->
    <script type="text/javascript" src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript">
        function showMsg(flag) {
            if (flag == 0) {
                $('.successBox').css('display', 'block');
            } else {
                $('.successBox').css('display', 'none');
            }
        }
    </script>

</body>

</html>
{% endblock %}

web/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
  {% include 'common/header1.html'   %}
{% endblock %}
{% block content %}

<!-- header section end -->
<!-- services section start -->
<div class="services_section layout_padding padding_bottom_0">
  <div class="container">
    <h1 class="blog_text" style="font-size: xxxxx-large;">Blog</h1>
    <div class="row">
      {% for blog in blog %}
      <div class="col-lg-4">
        <div class="call_box">
          <div class="call_image"><img src="{{blog.img.url}}"></div>
          <h2 class="emergency_text" style="color: red;">{{blog.title}}</h2>
          <h1 class="call_text">{{blog.description}}</h1>
          <p class="dolor_text">09297766556</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

web/templates/booking.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
  {% include 'common/header1.html'   %}
{% endblock %}
{% block content %}
  <h1>Booking Confirmation</h1>
  <p>Thank you for booking with us!</p>
  <p>Your booking details:</p>
  <p>Doctor: {{ doctor.name }}</p>
  <p>Date: {{ date }}</p>
  <p>Time: {{ time }}</p>
  <p>Location: {{ location }}</p>
{% endblock %}

web/templates/booking_notification.html
{% autoescape off %} 

Dear {{owner}},

We are pleased to inform you that your room has been booked by {{tenant.username}}. The booking details are as follows:

Room: {{room.room_number}}
Apartment name : {{room.apartment.apartment_name}}
Tenant contacts: {{tenant.phone}} or {{tenant.email}}
Book Time: {{time}} (UTC+0300)
Please review the booking details and confirm your acceptance by replying to this email. If you have any questions or concerns, please do not hesitate to contact us.

Thank you for your time and consideration.

Sincerely,
RBMS
{% endautoescape %}   

web/templates/contact_info.html
{% extends 'base.html' %} {% load static %} {% block header %} {% include
'common/header1.html' %} {% endblock %} {% block content %}

<div class="contact_section layout_padding">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <form action="" method="post">
          {% csrf_token %}
          <h1 class="contact_text">Contact Us</h1>
          <form action="{%static '/action_page.php' %}">
          <div class="form-group">
            <input type="text" class="email-bt" placeholder="Name" name="Name" />
          </div>
          <div class="form-group">
            <input type="text" class="email-bt" placeholder="Email" name="Email" />
          </div>
          <div class="form-group">
            <input type="text" class="email-bt" placeholder="Subject" name="Email" />
          </div>
          <div class="form-group">
            <textarea class="massage-bt" placeholder="Massage" rows="5" id="comment" name="text"></textarea>
          </div>
        </form>
        <div class="main_bt"><a href="#">Send</a></div></form>
        
      </div>
      <div class="col-md-6">
        <h1 class="contact_text">What syas our peasant</h1>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <h2 class="selfideno_text">Selfideno</h2>
              <div class="client_main">
                <div class="image_5">
                  <img src="{%static 'images/img-5.png' %}" />
                </div>
                <p class="lorem_ipsum_text">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                  irure dolor in reprehenderit in voluptate velit esse cillum
                  dolore eu fugiat nulla pariatur. Excepteur
                </p>
                <div class="quote_icon">
                  <img src="{%static 'images/quote-icon.png' %}" />
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <h2 class="selfideno_text">Selfideno</h2>
              <div class="client_main">
                <div class="image_5">
                  <img src="{%static 'images/img-5.png' %}" />
                </div>
                <p class="lorem_ipsum_text">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                  irure dolor in reprehenderit in voluptate velit esse cillum
                  dolore eu fugiat nulla pariatur. Excepteur
                </p>
                <div class="quote_icon">
                  <img src="{%static 'images/quote-icon.png' %}" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="appointment_section">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h3 class="need_text">Need a doctor for check-Up</h3>
        <h1 class="make_text">Make An Appointment & You're Done</h1>
      </div>
      <div class="col-md-6">
        <div class="appointment_bt_main">
          <div class="appointment_bt"><a href="#">Get Appointment</a></div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

web/templates/doctor.html
{% extends 'base1.html' %} 
{% load static %}
{% block header %}
  {% include 'common/header1.html'   %}
{% endblock %}
{% block content1 %}

<!--=== Team v1 ===-->

<div class="container content-md team-v1">
  <ul class="list-unstyled row">
    {% for doctor in doctor %}
    <li class="col-sm-3 col-xs-6" style="margin-bottom: 30px">
      <div class="team-img">
        <img class="img-responsive" src="{{ doctor.img.url }}" alt="" />
        <ul>
          <li>
            <a href="https://www.twitter.com"
              ><i class="icon-custom icon-sm rounded-x fa fa-twitter"></i
            ></a>
          </li>
          <li>
            <a href="https://www.facebook.com"
              ><i class="icon-custom icon-sm rounded-x fa fa-facebook"></i
            ></a>
          </li>
          <li>
            <a href="https://www.instagram.com"
              ><i class="icon-custom icon-sm rounded-x fa fa-instagram"></i
            ></a>
          </li>
        </ul>
      </div>
      <h3>{{ doctor.name }}</h3>
      <h4>{{ doctor.description }}</h4>
      <p>{{ doctor.specialize }}</p>
      <a href="{% url 'web:booking' doctor_id=doctor.id %}" class="btn btn-primary">Book Now</a>
    </li>
    {% endfor %}
  </ul>
</div>

<!-- doctor section end -->
<!-- footer section start -->
<!-- info section -->
{% endblock %}

web/templates/sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link
      rel="stylesheet"
      href="{%static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css' %}"
    /> -->
    <link rel="stylesheet" href="{%static 'css/style4.css' %}" />
    <title>Modern Login Page | AsmrProg</title>
  </head>

  <body>
    <div class="container" id="container">
      <div class="form-container sign-up">
        <form method="post" action="{% url 'accounts:register' %}">
            {% csrf_token %}
          <h1>Create Account</h1>
          <!-- {{ form.as_p }} -->
          <select name="gender" id="">
            <option value="Male">male</option>
            <option value="Female">female</option>
            <option value="Other">other</option>
          </select>
          <input type="text" placeholder="Full name" name="full_name"/>
          <input type="text" placeholder="username" name="username"/>
          <input type="tel" placeholder="phone number" name="phone"/>
          <input type="email" placeholder="Email" name="email" />
          <input type="password" placeholder="Password" name="password1" />
          <input type="password" placeholder="confirm_Password" name="password2" />
          <button>Sign Up</button>
        </form>
      </div>
      <div class="form-container sign-in">
        <form method="post" action="{% url 'accounts:sign_in' %}">
            {% csrf_token %}
          <h1>Sign In</h1>
          <div class="social-icons">
            <a href="#" class="icon"
              ><i class="fa-brands fa-google-plus-g"></i
            ></a>
            <a href="#" class="icon"><i class="fa-brands fa-facebook-f"></i></a>
            <a href="#" class="icon"><i class="fa-brands fa-github"></i></a>
            <a href="#" class="icon"
              ><i class="fa-brands fa-linkedin-in"></i
            ></a>
          </div>
          <span>or use your email password</span>
          <input type="text" placeholder="username" name="user_name" />
          <input type="password" placeholder="Password" name="password"/>
          <a href="#">Forget Your Password?</a>
          <button>Sign In</button>
        </form>
      </div>
      <div class="toggle-container">
        <div class="toggle">
          <div class="toggle-panel toggle-left">
            <h1>Welcome Back!</h1>
            <p>Enter your personal details to use all of site features</p>
            <button class="hidden" id="login">Sign In</button>
          </div>
          <div class="toggle-panel toggle-right">
            <h1>Hello, Friend!</h1>
            <p>
              Register with your personal details to use all of site features
            </p>
            <button class="hidden" id="register">Sign Up</button>
          </div>
        </div>
      </div>
    </div>

    <script src="{% static 'js/script1.js' %}"></script>
  </body>
</html>